#!/usr/bin/env ruby
#^syntax detection

forge "http://forge.puppetlabs.com"

mod 'puppetlabs/stdlib'
mod 'puppetlabs/apt'
mod 'puppetlabs/concat'
mod 'git', :git => 'https://github.com/example42/puppet-git.git'
mod 'mysql', :git => 'https://github.com/example42/puppet-mysql.git'
mod 'apache', :git => 'https://github.com/example42/puppet-apache.git'
mod 'php', :git => 'https://github.com/example42/puppet-php.git'
mod 'txtcmdr', :git => 'https://github.com/lbhurtado/puppet-txtcmdr.git'
mod 'custom', :git => 'https://github.com/lbhurtado/puppet-txtcmdr-custom.git'
mod 'composer', :git => 'https://github.com/lbhurtado/puppet-txtcmdr-composer.git'
mod 'symfony', :git => 'https://github.com/vagrantee/puppet-symfony.git'
mod 'smstools', :git => 'https://github.com/lbhurtado/puppet-smstools.git'
